const datos = [
  {
    "Titol": "Autor",
    "Anarquia y lucha antipolítica": "Acácio Augusto",
    "Manual de prácticas del autobús": "Gabriel Weber",
    "Muerte de la democracia": "Franco \"Bifo\" Berardi, Lior Zalis, Diego Posada",
    "Biblioteca de mi casa": "Walter Benjamin, Nathanael Araujo",
    "Biblioteca de casa meva": "Walter Benjamin, Nathanael Araujo",
    "La terra dona, la terra vol": "Antonio Nêgo Bispo",
    "50+1 Blues Llum Ombra": "Enric Puyoles",
    "Plaga": "Grupo de Investigación Ecologías Culturales PEI",
    "Descontentos en la cultura": "Sarah Wood",
    "The incomplete lexicon of art": "Lucas Kröeff",
    "Nada sino diseño": "Luis Alegre",
    "Louise Bourgeois y modos feministas de crear": "Gabriela Barzaghi De Laurentiis",
    "Exiliados del tiempo lento": "Vivian Abenshushan",
    "物博士预言的末日": "Fabio Zimbres",
    "Roube o livro enquanto o sol está nascendo no horizonte": "David Horvitz",
    "De la subcontratar": "Nick Thurston",
    "RES01 - res_és_nostre": "modular_juns",
    "Les Jardins et la Nuit": "Vicente Franz Cecim",
    "Os Jardins e a Noite": "Vicente Franz Cecim"
  },
  {
    "Titol": "Tipus",
    "Anarquia y lucha antipolítica": "Libro de bolsillo",
    "Manual de prácticas del autobús": "Llibre",
    "Muerte de la democracia": "Libro de bolsillo",
    "Biblioteca de mi casa": "Llibre",
    "Biblioteca de casa meva": "Llibre",
    "La terra dona, la terra vol": "Llibre",
    "50+1 Blues Llum Ombra": "Llibre",
    "Plaga": "Llibre",
    "Descontentos en la cultura": "Llibre",
    "The incomplete lexicon of art": "Llibre",
    "Nada sino diseño": "Llibre",
    "Louise Bourgeois y modos feministas de crear": "Llibre",
    "Exiliados del tiempo lento": "Llibre",
    "物博士预言的末日": "Comic",
    "Roube o livro enquanto o sol está nascendo no horizonte": "Llibre",
    "De la subcontratar": "",
    "RES01 - res_és_nostre": "Llibre",
    "Les Jardins et la Nuit": "Llibre",
    "Os Jardins e a Noite": "Llibre"
  },
  {
    "Titol": "Any",
    "Anarquia y lucha antipolítica": 2019,
    "Manual de prácticas del autobús": 2024,
    "Muerte de la democracia": 2021,
    "Biblioteca de mi casa": 2023,
    "Biblioteca de casa meva": 2023,
    "La terra dona, la terra vol": 2025,
    "50+1 Blues Llum Ombra": 2024,
    "Plaga": 2021,
    "Descontentos en la cultura": 2022,
    "The incomplete lexicon of art": 2020,
    "Nada sino diseño": 2022,
    "Louise Bourgeois y modos feministas de crear": 2020,
    "Exiliados del tiempo lento": 2024,
    "物博士预言的末日": 2019,
    "Roube o livro enquanto o sol está nascendo no horizonte": 2019,
    "De la subcontratar": 2019,
    "RES01 - res_és_nostre": 2023,
    "Les Jardins et la Nuit": 2019,
    "Os Jardins e a Noite": 2019
  },
  {
    "Titol": "Format",
    "Anarquia y lucha antipolítica": "12 × 18 cm",
    "Manual de prácticas del autobús": "17 x 24 cm",
    "Muerte de la democracia": "14 x 22 cm",
    "Biblioteca de mi casa": "24 x 17 cm",
    "Biblioteca de casa meva": "25 x 17 cm",
    "La terra dona, la terra vol": "15 x 21 cm",
    "50+1 Blues Llum Ombra": "14 x 22 cm",
    "Plaga": "15 x 21 cm",
    "Descontentos en la cultura": "15 x 21 cm",
    "The incomplete lexicon of art": "14 x 22 cm",
    "Nada sino diseño": "10,5 x 17 cm",
    "Louise Bourgeois y modos feministas de crear": "15 x 21 cm",
    "Exiliados del tiempo lento": "19 x 12 m",
    "物博士预言的末日": "15 x 21 cm",
    "Roube o livro enquanto o sol está nascendo no horizonte": "15 x 10 cm",
    "De la subcontratar": "20 x 13 cm",
    "RES01 - res_és_nostre": "15 x 21 cm",
    "Les Jardins et la Nuit": "30 x 21 cm",
    "Os Jardins e a Noite": "30 x 21 cm"
  },
  {
    "Titol": "Pàgines",
    "Anarquia y lucha antipolítica": 64,
    "Manual de prácticas del autobús": 120,
    "Muerte de la democracia": 76,
    "Biblioteca de mi casa": 64,
    "Biblioteca de casa meva": 64,
    "La terra dona, la terra vol": 98,
    "50+1 Blues Llum Ombra": 260,
    "Plaga": 98,
    "Descontentos en la cultura": 80,
    "The incomplete lexicon of art": "",
    "Nada sino diseño": 320,
    "Louise Bourgeois y modos feministas de crear": 184,
    "Exiliados del tiempo lento": 188,
    "物博士预言的末日": 24,
    "Roube o livro enquanto o sol está nascendo no horizonte": 48,
    "De la subcontratar": 145,
    "RES01 - res_és_nostre": 48,
    "Les Jardins et la Nuit": 158,
    "Os Jardins e a Noite": 158
  },
  {
    "Titol": "ISBN",
    "Anarquia y lucha antipolítica": "978-85-53109-18-0",
    "Manual de prácticas del autobús": "120978-84-126845-4-4",
    "Muerte de la democracia": "978-85-5109-21-0",
    "Biblioteca de mi casa": "978-84-126845-2-0",
    "Biblioteca de casa meva": "978-84-126845-2-1",
    "La terra dona, la terra vol": "978-84-126845-5-1",
    "50+1 Blues Llum Ombra": "978-85-53109-26-5",
    "Plaga": "fake-001",
    "Descontentos en la cultura": "978-85-53109-17-3",
    "The incomplete lexicon of art": "978-85-53109-23-4",
    "Nada sino diseño": "978-85-53109-24-1",
    "Louise Bourgeois y modos feministas de crear": "978-84-126845-1-3",
    "Exiliados del tiempo lento": "978-84-126845-3-7",
    "物博士预言的末日": "978-85-53109-16-6",
    "Roube o livro enquanto o sol está nascendo no horizonte": "978-3-945900-28-4",
    "De la subcontratar": "978-8-412684-50-6",
    "RES01 - res_és_nostre": "978-85-53109-25-8",
    "Les Jardins et la Nuit": "fake-002",
    "Os Jardins e a Noite": "fake-002"
  },
  {
    "Titol": "Disseny de coberta",
    "Anarquia y lucha antipolítica": "Felipe de Leonardo",
    "Manual de prácticas del autobús": "Bia Bittencourt",
    "Muerte de la democracia": "Mantraste",
    "Biblioteca de mi casa": "Bia Bittencourt",
    "Biblioteca de casa meva": "Bia Bittencourt",
    "La terra dona, la terra vol": "Estúdio Casa Rex",
    "50+1 Blues Llum Ombra": "Bia Bittencourt",
    "Plaga": "Estudio Ara",
    "Descontentos en la cultura": "Bia Bittencourt",
    "The incomplete lexicon of art": "Lucas Kröeff",
    "Nada sino diseño": "Sara Farias",
    "Louise Bourgeois y modos feministas de crear": "Lucas Kröeff",
    "Exiliados del tiempo lento": "Bia Bittencourt",
    "物博士预言的末日": "Bia Bittencourt",
    "Roube o livro enquanto o sol está nascendo no horizonte": "Edition Taube",
    "De la subcontratar": "Bia Bittencourt",
    "RES01 - res_és_nostre": "Bia Bittencourt",
    "Les Jardins et la Nuit": "Lucas Kröeff",
    "Os Jardins e a Noite": "Lucas Kröeff"
  },
  {
    "Titol": "Edició",
    "Anarquia y lucha antipolítica": "Bia Bittencourt",
    "Manual de prácticas del autobús": "Bia Bittencourt",
    "Muerte de la democracia": "Bia Bittencourt, Laura Del Vecchio",
    "Biblioteca de mi casa": "Bia Bittencourt",
    "Biblioteca de casa meva": "Bia Bittencourt",
    "La terra dona, la terra vol": "Bia Bittencourt",
    "50+1 Blues Llum Ombra": "Jordi Puyoles Calafell",
    "Plaga": "Macba",
    "Descontentos en la cultura": "Bia Bittencourt",
    "The incomplete lexicon of art": "Lucas Kröeff",
    "Nada sino diseño": "Diogo Montenegro",
    "Louise Bourgeois y modos feministas de crear": "Bia Bittencourt",
    "Exiliados del tiempo lento": "Bia Bittencourt",
    "物博士预言的末日": "Bia Bittencourt",
    "Roube o livro enquanto o sol está nascendo no horizonte": "",
    "De la subcontratar": "",
    "RES01 - res_és_nostre": "No Libos + Hivern Discs",
    "Les Jardins et la Nuit": "Bia Bittencourt",
    "Os Jardins e a Noite": "Bia Bittencourt"
  },
  {
    "Titol": "Traducció",
    "Anarquia y lucha antipolítica": "John O'Kuinghttons",
    "Manual de prácticas del autobús": "John O'Kuinghttons",
    "Muerte de la democracia": "John O'Kuinghttons",
    "Biblioteca de mi casa": "Bia Bittencourt",
    "Biblioteca de casa meva": "Jordi Puyoles Calafell",
    "La terra dona, la terra vol": "Jèssica Cañagueral Pallarés",
    "50+1 Blues Llum Ombra": "",
    "Plaga": "",
    "Descontentos en la cultura": "John O'Kuinghttons",
    "The incomplete lexicon of art": "",
    "Nada sino diseño": "John O'Kuinghttons",
    "Louise Bourgeois y modos feministas de crear": "John O'Kuinghttons",
    "Exiliados del tiempo lento": "",
    "物博士预言的末日": "Yaya Liu",
    "Roube o livro enquanto o sol está nascendo no horizonte": "Bia Bittencourt",
    "De la subcontratar": "Google Translator",
    "RES01 - res_és_nostre": "",
    "Les Jardins et la Nuit": "",
    "Os Jardins e a Noite": ""
  },
  {
    "Titol": "Imprès a",
    "Anarquia y lucha antipolítica": "Podiprint, Màlaga",
    "Manual de prácticas del autobús": "Podiprint, Màlaga",
    "Muerte de la democracia": "Podiprint, Màlaga",
    "Biblioteca de mi casa": "Podiprint, Màlaga",
    "Biblioteca de casa meva": "Podiprint, Màlaga",
    "La terra dona, la terra vol": "Podiprint, Màlaga",
    "50+1 Blues Llum Ombra": "Podiprint, Màlaga",
    "Plaga": "Barcelona",
    "Descontentos en la cultura": "Podiprint, Màlaga",
    "The incomplete lexicon of art": "Podiprint, Màlaga",
    "Nada sino diseño": "MB&F",
    "Louise Bourgeois y modos feministas de crear": "Podiprint, Màlaga",
    "Exiliados del tiempo lento": "Podiprint, Màlaga",
    "物博士预言的末日": "La Escocesa",
    "Roube o livro enquanto o sol está nascendo no horizonte": "",
    "De la subcontratar": "Podiprint, Màlaga",
    "RES01 - res_és_nostre": "Do the print",
    "Les Jardins et la Nuit": "Podiprint, Màlaga",
    "Os Jardins e a Noite": "Podiprint, Màlaga"
  },
  {
    "Titol": "Tècnica d’impressió",
    "Anarquia y lucha antipolítica": "Impresión Digital",
    "Manual de prácticas del autobús": "Impresión Digital",
    "Muerte de la democracia": "Impresión Digital",
    "Biblioteca de mi casa": "Impresión Digital",
    "Biblioteca de casa meva": "Impresión Digital",
    "La terra dona, la terra vol": "Impresión Digital",
    "50+1 Blues Llum Ombra": "Impresión Digital",
    "Plaga": "Impresión Digital",
    "Descontentos en la cultura": "Impresión Digital",
    "The incomplete lexicon of art": "Impresión Digital",
    "Nada sino diseño": "Offset",
    "Louise Bourgeois y modos feministas de crear": "Impresión Digital",
    "Exiliados del tiempo lento": "Impresión Digital",
    "物博士预言的末日": "Risograph",
    "Roube o livro enquanto o sol está nascendo no horizonte": "Offset",
    "De la subcontratar": "Impresión Digital",
    "RES01 - res_és_nostre": "Risograph",
    "Les Jardins et la Nuit": "Impressió digital",
    "Os Jardins e a Noite": "Impresión Digital"
  },
  {
    "Titol": "Més info",
    "Anarquia y lucha antipolítica": "https://www.nolibros.org/product/anarquia-y-lucha-antipolitica/10?cs=true&cst=custom",
    "Manual de prácticas del autobús": "https://www.nolibros.org/product/manual-de-pr-cticas-del-autob-s-474-jacar-copacabana/16?cs=true&cst=custom",
    "Muerte de la democracia": "https://www.nolibros.org/product/muerte-de-la-democracia/9?cs=true&cst=custom",
    "Biblioteca de mi casa": "https://www.nolibros.org/product/biblioteca-de-mi-casa/3?cs=true&cst=custom",
    "Biblioteca de casa meva": "https://www.nolibros.org/product/biblioteca-de-mi-casa/3?cs=true&cst=custo",
    "La terra dona, la terra vol": "https://www.nolibros.org/product/la-terra-dona-la-terra-vol-antonio-nego-bispo/18?cs=true&cst=custom",
    "50+1 Blues Llum Ombra": "",
    "Plaga": "https://www.macba.cat/es/exposiciones/plaga-2/",
    "Descontentos en la cultura": "https://www.nolibros.org/product/descontentos-en-la-cultura/5?cs=true&cst=custom",
    "The incomplete lexicon of art": "https://www.nolibros.org/product/incomplete-lexicon-of-art/8?cs=true&cst=custom",
    "Nada sino diseño": "https://www.nolibros.org/product/nada-sino-diseno/6?cs=true&cst=custom",
    "Louise Bourgeois y modos feministas de crear": "https://www.nolibros.org/product/louise-bourgeois-y-modos-feministas-de-crear/7?cs=true&cst=custom",
    "Exiliados del tiempo lento": "https://www.nolibros.org/product/exiliados-del-tiempo-lento/1?cs=true&cst=custom",
    "物博士预言的末日": "",
    "Roube o livro enquanto o sol está nascendo no horizonte": "https://www.nolibros.org/product/roube-o-livro/11?cs=true&cst=custom",
    "De la subcontratar": "https://www.nolibros.org/product/de-la-subcontratar/4?si=true",
    "RES01 - res_és_nostre": "https://www.nolibros.org/product/res01-res-s-nostre-modular-juns/17?cs=true&cst=custom",
    "Les Jardins et la Nuit": "https://www.nolibros.org/product/les-jardins-et-la-nuit/14?cs=true&cst=custom",
    "Os Jardins e a Noite": "https://www.nolibros.org/product/les-jardins-et-la-nuit/14?cs=true&cst=custom"
  }
];